server:
  port: 0

script:
  task:
    remoteTask:
      work: false
    runTime:
      home: ../runtime


baidu:
  map:
    ak: fM8NAbY4zKML7dgMgWKDkOcmb0Dql6GU,x98fEy21xWYzsdA4FpDfMu81saHXe2O8


logging:
  file:
    name: ../logs/TaskClient.log


webfetch:
  url:
    - https://proxy.up1.workers.dev
